Setup command line interface
dannypsnl/violet pull request #12
Opened 2022-10-18 13:55 UTC by shana0440

2022-10-18 16:05 UTC, dannypsnl requested changes
Great start! I would need a list of what gets done in the PR, corresponding to #6, and you can click the checkbox directly when you feel you have completed a task :).

By the way, you can try [magic-racket](https://marketplace.visualstudio.com/items?itemName=evzen-wybitul.magic-racket) and [racket-langserver](https://github.com/jeapostrophe/racket-langserver) as development tool.

2022-10-18 16:05 UTC, dannypsnl commented on build.rkt
> +    (directory-list dir-path)))
I guess you would like `fold-files` for the case

2022-10-18 16:05 UTC, dannypsnl commented on command.rkt
> +        (cons "compile" file-path))])))
I guess later this would be in `main.rkt`?

2022-10-18 16:05 UTC, dannypsnl commented on compile.rkt
> +  (println file-path))
I guess this exactly wants the `compile-all` function in `main.rkt`

2022-10-18 16:05 UTC, dannypsnl commented on compile.rkt
> +  (println file-path))
and the eof

2022-10-18 17:55 UTC, shana0440 commented
@dannypsnl updated, thanks.
Rename `command.rkt` to `main.rkt` and handle the compile will be the follow up PR, it likely is a huge work for me so want to separate to different PR.

2022-10-19 02:34 UTC, dannypsnl commented
> @dannypsnl updated, thanks.
> Rename `command.rkt` to `main.rkt` and handle the compile will be the follow up PR, would like to make PR small as possible since I'm not familiar with racket.

Get it

2022-10-19 02:37 UTC, merged