Handle compile command
dannypsnl/violet pull request #13
Opened 2022-10-19 11:31 UTC by shana0440

This PR handle following two things.
- handle compile command.
- let main module invoke command module.

The build command will handle in follow up PR.

2022-10-19 13:54 UTC, dannypsnl requested changes

2022-10-19 13:54 UTC, dannypsnl commented on command.rkt
> +    (compile-all file-path)]))
I think maybe there has no need for this two-phase thing? Just
```rkt
  (command-line
      #:program "violet"
      #:args (subcommand . rest)
      (match subcommand
      ["build"
        (command-line
          #:argv rest
          #:args (dir-path)
          (build dir-path))]
      ["compile"
        (command-line
          #:argv rest
          #:args (file-path)
          (compile-all file-path))]))
```

BTW, `compile-all` maybe should be renamed to something that says "compile source code to object file"

2022-10-19 15:36 UTC, shana0440 commented on command.rkt
> +    (compile-all file-path)]))
I prefer separate to two phase in case handler grow in the future.
for example, need to depends on flag to call different function, if we put it in one phase it will difficult to read (at least for me).

2022-10-19 22:59 UTC, dannypsnl commented on command.rkt
> +    (compile-all file-path)]))
I think that's too general for now, in the first few years, I can't see why we would need different behavior for the same command. And we always can use higher-order functions, for example:
```rkt
(define ((handle-command build compile) usecase)
  ...
  ["build" (build dir-path)]
  ["compile" (compile file-path)])
```

2022-10-23 00:50 UTC, shana0440 commented on command.rkt
> +    (compile-all file-path)]))
OK, let's use one function to parse and execute commands for now, we can change it when we need.

2022-10-23 00:50 UTC, shana0440 commented
@dannypsnl  updated thanks.

2022-10-23 01:06 UTC, dannypsnl approved these changes

2022-10-23 01:07 UTC, merged