Top level syntax
dannypsnl/violet pull request #39
Opened 2022-12-24 20:19 UTC by rayshih

For #31 

The current implementation simply reuses the linked list structure. It typechecks but doesn't not really generate list of bindings to evaluate/reference. To have that, one way is to find out a way to carry out all top level types/bindings from Env/Ctx after "typechecking" the module. Another layer of `infer`/`check` function?

2022-12-25 03:58 UTC, dannypsnl requested changes

2022-12-25 03:58 UTC, dannypsnl commented on src/Violet/Lexer.idr
> +  | VModule             -- module
`VTModule`

2022-12-25 22:00 UTC, rayshih commented
Output of latest version

```
% ./build/exec/violet check example/module.vt
Nat : U
zero : Nat
suc : (_ : Nat) → Nat
SomethingElse : U
id : (A : U) → (_ : A) → A
main : Nat
```

2022-12-25 22:16 UTC, rayshih commented
syntax design proposal 1:

```
module AModule (Nat, id)

data Nat
  | zero : Nat
  | suc : Nat → Nat;

data SomethingElse;

let id : (A : U) → (_ : A) → A = λ A x . x;
```


syntax design proposal 2:

```
module AModule

export
data Nat
  | zero : Nat
  | suc : Nat → Nat;

data SomethingElse;

export
let id : (A : U) → (_ : A) → A = λ A x . x;
```

2022-12-25 23:09 UTC, dannypsnl commented
I would say the second one is more flexible in daily developing flow, considering a file is pretty long, and dependent-type roughly requires us define by order. Thus, the first design will make export places and definitions far from each other.

2022-12-27 01:07 UTC, rayshih commented
I think it makes a little more sense to handle the module system in another PR and leave this one to focus on the top level syntax

2022-12-27 01:36 UTC, dannypsnl commented
Sure

2022-12-27 01:51 UTC, dannypsnl commented on src/Violet/Core.idr
> +      Just a => pure (a, emptyEnvAndCtx)
Shouldn’t that return ctx and env in the scope?

2022-12-27 02:01 UTC, dannypsnl requested changes

2022-12-27 02:01 UTC, dannypsnl commented on src/Violet/Syntax.idr
> +data ModuleInfoRaw = MkModuleInfoRaw Name
probably should be a record for later extension?

2022-12-27 02:01 UTC, dannypsnl commented on src/Violet/Syntax.idr
>  toTm : Raw -> Tm
I guess this exactly can use `Cast Raw Tm`

2022-12-27 02:03 UTC, dannypsnl requested changes
Another thing is I will like to remove a raw case `postulate`, it would be in core term & top-level raw, but not in `Raw`

2022-12-27 11:53 UTC, rayshih commented on src/Violet/Syntax.idr
> +data ModuleInfoRaw = MkModuleInfoRaw Name
I'm thinking the same. I'd like to change it in the later PR since we'll need to change this again either ways

2022-12-27 11:54 UTC, rayshih commented on src/Violet/Core.idr
> +      Just a => pure (a, emptyEnvAndCtx)
Not sure if this is still a concern

2022-12-27 11:56 UTC, dannypsnl commented on src/Violet/Syntax.idr
> +data ModuleInfoRaw = MkModuleInfoRaw Name
Ok

2022-12-27 12:01 UTC, dannypsnl commented on src/Violet/Core.idr
> +      Just a => pure (a, emptyEnvAndCtx)
Yes, I guess just rebuild the module context on it

This is not important than

2022-12-27 16:13 UTC, merged