elim: syntax & core term
dannypsnl/violet pull request #45
Opened 2022-12-28 07:27 UTC by CYBAI

Fix #24

2022-12-28 09:15 UTC, dannypsnl requested changes
You have to use relate #24 here, and add a description

2022-12-28 09:17 UTC, dannypsnl commented
Else the code is ready to merge

2022-12-28 22:12 UTC, rayshih commented on src/Violet/Core.idr
> +    Elim t cases => ?todo2
I assume this will be implemented later in the same PR right?

2022-12-29 03:17 UTC, dannypsnl commented on src/Violet/Core.idr
> +    Elim t cases => ?todo2
There should have another PR, else would have too many conflict

2022-12-29 03:17 UTC, dannypsnl commented on src/Violet/Core.idr
> +    Elim t cases => ?todo2
Let me convert this PR to ready first

2022-12-29 04:51 UTC, CYBAI commented on src/Violet/Core.idr
> +    Elim t cases => ?todo2
yeah, let's make this PR only for syntax and parser and let's implement `eval` and `infer` later? WDYT?

2022-12-29 04:55 UTC, merged