[module_system] traverse and parse all dependent modules
dannypsnl/violet pull request #78
Opened 2023-02-12 00:18 UTC by rayshih

```
% ./build/exec/violet check AModule
parse module ./example/AModule.vt
parse module ./example/Base.vt
parse module ./example/Lib.vt
parse module ./example/Core.vt
Nat : U
zero : Nat
suc : Nat → Nat
id : {A : U} → (x : A) → A
main : Nat
```

------

Next step: topological sort and compile

------

Few topics to discuss:

1. the mapping from module name to filepath, including the root of the "package"
2. Error handling beyond the one file typechecker/compiler
3. Scope of each module -> simple one could be exposing all top level decls to the only one global ctx/env

2023-02-12 05:28 UTC, dannypsnl requested changes

2023-02-12 05:28 UTC, dannypsnl commented on example/Base.vt
> +import Core
eof

2023-02-12 05:28 UTC, dannypsnl commented on example/Core.vt
> +module Core
eof

2023-02-12 05:28 UTC, dannypsnl commented on example/Lib.vt
> +import Core
eof

2023-02-12 12:58 UTC, rayshih commented
> 1. the mapping from module name to filepath, including the root of the "package"

The essential question is: given a module name, where to lookup the corresponding file. And there are 2 smaller questions:

(Assuming the module to filepath mapping is mostly replacing `.` to `/`
a. should we introduce a new argument for specifying the root directory of all modules?
b. if we extend this question, then the next question is do we want to introduce a package system? as in, every package has its own root directory.

> 2. Error handling beyond the one file typechecker/compiler

The current error handling is limited to one file, and I haven't figured out a way to put cross module errors. I think the problem is: `App` monad is only about one file. Should we extend it to multiple files? or do you have other ideas?


> 3. Scope of each module -> simple one could be exposing all top level decls to the only one global ctx/env

Each module has its own scope of top decls, to run a typecheck of a module A which depends on module B, the exported decls from B needs to also be in the scope while typechecking module A. The easiest solution is

a. assume all top decls are exported.
b. bring all dependent module top decls into the current scope.

But there are problem's like if there are 2 decls from different modules having the same name, which one to take?

Alternatively we can create a lookup map. But in any case, we will need to have a resolution method if there is naming conflict

2023-02-12 13:35 UTC, dannypsnl commented
> 1. the mapping from module name to filepath, including the root of the "package"

Both answers are yes, we should introduce package concept, which is a collection of modules. A package is a root of files, and should have a meta file to describe how to deal with these stuff.

> 2. Error handling beyond the one file typechecker/compiler

I am not quite sure for the details now, but I have some constraints in mind that you can follow
1. The module will not get check, if its dependencies get failed
2. But each dependencies are independent 

> 3. Scope of each module -> simple one could be exposing all top level decls to the only one global ctx/env

Keep the simple solution for now since name resolution is a complicated thing, we will need an isolated issue to track it, you can open one and describe the problem.

2023-02-15 13:27 UTC, rayshih commented
let's land this PR first and I'll continue on the toposort and then the ctx/env propagation

2023-02-15 13:34 UTC, dannypsnl requested changes

2023-02-15 13:34 UTC, dannypsnl commented on src/Main.idr
> +	-- (raw, source) <- parseModuleFile filename
Maybe we don't need this unused code?

2023-02-15 13:34 UTC, dannypsnl commented on src/Main.idr
> +	modules <- parseDepModules "./example" empty $ singleton filename
Please mark this `"./example"` hard coding with TODO or FIXME

2023-03-06 04:44 UTC, dannypsnl approved these changes

2023-03-06 04:44 UTC, merged